name: CI

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:

jobs:
  ci:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install pre-commit

      - run: pre-commit run --all-files

      - run: cargo build --release
      - run: cargo test -- --ignored

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/viy
          generate_release_notes: true
